@endpoint = https://rbckrp3od8.execute-api.us-east-1.amazonaws.com/prod

GET {{endpoint}}/hello
###

POST {{endpoint}}/spaces
Content-Type: 'application/json',

{
    "location": "Philippines",
    "name": "Best Vacation location"
}
###

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?location=London
###